server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:animal_renting_db}
    url: jdbc:postgresql://${APP_DB_URL:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:animal_app_db}
#    username: postgres
    username: animals_user
    password: 2140
  jpa:
    hibernate:
#      ddl-auto: update
      hbm2ddl:
        auto: update
    openInView: true
    show_sql: true
    generate-ddl: true
  data:
    jpa:
      repositories.enabled: true

service:
  ui:
    url: ${FRONTEND_API_URL:http://localhost:4200}

security:
  jwt:
    token:
      secretkey: ${SECRET_KEY:wipjd03kmv[wh567gmcvf2p0fh<niyedjgvdckjhkkhVvj;'\986546&*6865&^}
      tokendurationminutes: ${TOKEN_DURATION_MINUTES:600}
springdoc:
  packagesToScan: com.animalrenting
  pathsToMatch: /**
  api-docs:
    path: /api-docs